Swift: Workaround Swift 5.2 + 5.3 swiftinterface bug
With envoy-mobile built from Xcode 11.5, we are unable to consume it
with Xcode 12.0 beta 3. I'm hoping this fixes it, the errors appear
related:

```
deps/cache/dependencies/Envoy/current/Envoy.framework/Modules/Envoy.swiftmodule/x86_64.swiftinterface:137:28: error: overriding declaration requires an 'override' keyword
  @objc convenience public init()
                           ^
                           override
deps/cache/dependencies/Envoy/current/Envoy.framework/Modules/Envoy.swiftmodule/x86_64.swiftinterface:38:33: note: overridden declaration is here
  @objc override dynamic public init()
                                ^
Modules/EnvoyFilters/Sources/EnvoyFilterManager.swift:1:8: error: failed to build module 'Envoy' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.22.4 clang-1200.0.25.1)'
import Envoy
       ^
```

This reverts commit 29d32d8f9215ec3420442667faad333d8794a4bf.

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>