core: update submodule ref
CI is broken because a dependency was deleted (fixed in upstream envoy):

```
ERROR: /private/var/tmp/_bazel_runner/03991942a29068e37f62096bf1731e9c/external/envoy/bazel/repositories.bzl:248:5: //external:tclap depends on @com_github_eile_tclap//:tclap in repository @com_github_eile_tclap which failed to fetch. no such package '@com_github_eile_tclap//': java.io.IOException: Error downloading [https://github.com/eile/tclap/archive/tclap-1-2-1-release-final.tar.gz] to /private/var/tmp/_bazel_runner/03991942a29068e37f62096bf1731e9c/external/com_github_eile_tclap/tclap-1-2-1-release-final.tar.gz: GET returned 404 Not Found
```

Signed-off-by: Michael Rebello <me@michaelrebello.com>