Update ios.yml
```
Run ls -lh dist/
 total 565672
-rw-r--r--  1 runner  staff   720B Aug 23 05:49 BUILD
-rw-r--r--  1 runner  staff   272M Aug 23 05:51 Envoy
drwxr-xr-x  3 runner  staff    96B Aug 23 05:51 Headers
drwxr-xr-x  3 runner  staff    96B Aug 23 05:51 Modules
```

```
Analyzing: target //examples/swift/hello_world:app (1 packages loaded, 0 targets configured)
 Analyzing: target //examples/swift/hello_world:app (16 packages loaded, 16 targets configured)
Analyzing: target //examples/swift/hello_world:app (16 packages loaded, 16 targets configured)
Analyzing: target //examples/swift/hello_world:app (29 packages loaded, 199 targets configured)
Analyzing: target //examples/swift/hello_world:app (29 packages loaded, 199 targets configured)
ERROR: /Users/runner/runners/2.157.0/work/envoy-mobile/envoy-mobile/dist/BUILD:18:25: in framework_imports attribute of apple_static_framework_import rule //dist:envoy_mobile_ios: attribute must be non empty
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a http_archive (rule definition at /private/var/tmp/_bazel_runner/1cddc09a5d52e3a104110a34c3ea37cb/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /private/var/tmp/_bazel_runner/1cddc09a5d52e3a104110a34c3ea37cb/external/envoy_api/bazel/envoy_http_archive.bzl:18:5
 - /private/var/tmp/_bazel_runner/1cddc09a5d52e3a104110a34c3ea37cb/external/envoy/bazel/repositories.bzl:23:5
 - /private/var/tmp/_bazel_runner/1cddc09a5d52e3a104110a34c3ea37cb/external/envoy/bazel/repositories.bzl:474:5
 - /private/var/tmp/_bazel_runner/1cddc09a5d52e3a104110a34c3ea37cb/external/envoy/bazel/repositories.bzl:148:5
 - /Users/runner/runners/2.157.0/work/envoy-mobile/envoy-mobile/WORKSPACE:51:1
ERROR: Analysis of target '//examples/swift/hello_world:app' failed; build aborted: Analysis of target '//dist:envoy_mobile_ios' failed; build aborted
INFO: Elapsed time: 40.579s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (44 packages loaded, 659 targets configured)
FAILED: Build did NOT complete successfully (44 packages loaded, 659 targets configured)
```

Signed-off-by: Michael Rebello <me@michaelrebello.com>